# This file contains the settings for the scripts in the project
openai_model: "RTX.qwen3:14b" # the model to use for the generation
with_date: true # boolean if the title should the date as a prefix
# the AI prompt for the generation
prompt:
  # the main prompt for the AI
  main: |
    Analyze the following text and generate a concise, informative title in the corresponding language
    Include the sender or author (max 20 characters) in the title
    Remove all stop words from the title
    Ensure the title is unique and free of duplicate information
    Keep the title under 127 characters
    Avoid using asterisks in the title
    Optimize the title for readability
    Check the title against filename conventions
    Re-read and further optimize the title if necessary
    Format your response like this: <title>GENERATED_TITLE</title>
    Return nothing more.
    Here is the text, it is contained between the ‘BEGIN: """‘ and ‘""" END‘ Tags.
  # the prompt part will be appended if the date should be included in the title using with_date: true
  with_date: |
    Analyze the text and find the date of the document
    Add the found date in form YYYY-MM-DD as a prefix to the document title
    If there is no date information in the document, use {current_date}
    For the generated title use the form: sender title
  # the prompt part will be appended if the date should not be included in the title using with_date: false
  no_date: |
    For the generated title use the form: sender title
  # the prompt before the content of the document will be appended
  pre_content: |
    BEGIN: """
  # the prompt after the content of the document will be appended
  post_content: |
    """ END:
